ARG VERSION=1.8.2.3
ARG REPO_BASE=https://www.kernel.org/pub/software/scm/git/



##### Create a base image for them all to use with common dependencies
FROM centos:7 as base
RUN yum install -y openssh-clients less curl more man
# Needed but present: curl more
# Just needed at runtime: man



##### Compile git in a bloated container
FROM base as build
RUN yum install -y make gcc autoconf \
    perl-error perl-ExtUtils-MakeMaker \
    wget asciidoc docbook2x emacs xmlto libgnome-keyring python2 pcre2 shadow \
    gettext-devel zlib-devel openssl-devel expat-devel curl-devel perl-devel

WORKDIR /build
ARG REPO_BASE
ARG VERSION
RUN wget $REPO_BASE/git-${VERSION}.tar.gz
RUN tar xzf git-${VERSION}.tar.gz

WORKDIR /build/git-${VERSION}
RUN autoconf
RUN ./configure
RUN make
RUN make man
RUN make install
RUN make install-man



##### Final small image, just copying everything needed from install
FROM base
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

COPY --from=build /usr/local /usr/local

