ARG VERSION=2.23.2

FROM bauk/git:fedora-${VERSION}

# Tools
RUN yum erase -y vim-minimal && yum install -y vim nano && yum clean -y all

# Tool setup
RUN git config --system core.editor vim

# git-filter-repo - needs git >= 2.22.0 but produces decent errors if not
RUN yum install -y python3 && yum clean -y all \
 && curl https://raw.githubusercontent.com/newren/git-filter-repo/master/git-filter-repo -o /usr/local/bin/git-filter-repo \
 && chmod +x /usr/local/bin/git-filter-repo \
 && curl https://raw.githubusercontent.com/newren/git-filter-repo/docs/man1/git-filter-repo.1 -o /usr/local/share/man/man1/git-filter-repo.1

# git-lfs - do a double curl to get the latest version available at the time
RUN curl -L $(curl -sS https://git-lfs.com/ | grep git-lfs-linux-amd64 | sed -r 's#.*"(https://[^"]*/)([^/"]*)".*#\1/\2 -o \2#' | head -1) \
 && tar -xzf *.tar.gz \
 && ./*/install.sh \
 && rm -rf *
